### ISSUE TITLE
Feel free to post issue here

### ISSUE THREAD

**Issue by Novestars** [Novestars/Neural_Pre_Processing#1]

**Comment by haibinswe** [comment]
Thanks for your excellent work. when will the pre-trained weights uploaded so that I can integrate it into my research?

**Comment by Novestars** [comment]
> Thanks for your excellent work. when will the pre-trained weights uploaded so that I can integrate it into my research?

I have uploaded the pre-trained weight, feel free to check it out

**Comment by zheng-sk** [comment]
Hello, thanks for making this code and pre-trained weights available! I tried to run it in python (not with a container), and had a ValueError: Buffer dtype mismatch, expected 'int_t' but got 'long long'. Changing the dtype of the image after loading does not seem to fix it. Any suggestions from your side? Thanks.

**Comment by zheng-sk** [comment]
> Hello, thanks for making this code and pre-trained weights available! I tried to run it in python (not with a container), and had a ValueError: Buffer dtype mismatch, expected 'int_t' but got 'long long'. Changing the dtype of the image after loading does not seem to fix it. Any suggestions from your side? Thanks.

Solved by adding 'image = sf.Volume(image)' after loading the image file with sf.load_volume..
